# Generated by Django 3.1.1 on 2020-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'StudentProgres', 'verbose_name_plural': 'StudentProgres'},
        ),
    ]
