# Generated by Django 3.1.1 on 2020-11-05 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_paymentinfo_amount'),
        ('course', '0012_auto_20201102_1121'),
        ('progress', '0002_auto_20201029_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProgre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=127, null=True)),
                ('partialcomplete', models.BooleanField(default=False)),
                ('fullcomplete', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TeacherProgres',
                'verbose_name_plural': 'TeacherProgres',
            },
        ),
    ]
