# Generated by Django 3.1.1 on 2020-11-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_teacherprogre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
