# Generated by Django 3.1.1 on 2020-11-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_delete_studentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Batches',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.AlterField(
            model_name='teacherprogre',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.batches'),
        ),
    ]
