# Generated by Django 3.1.1 on 2020-11-09 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_auto_20201109_0855'),
        ('progress', '0006_studentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolen', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, max_length=127, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.fileupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentProgres',
                'verbose_name_plural': 'StudentProgres',
            },
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
