# Generated by Django 3.1.1 on 2020-11-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_auto_20201109_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogres',
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress'},
        ),
        migrations.AlterModelOptions(
            name='teacherprogre',
            options={'verbose_name': 'Teacher Progress', 'verbose_name_plural': 'Teacher Progress'},
        ),
    ]
