# Generated by Django 3.1.1 on 2020-09-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
