# Generated by Django 3.1.1 on 2020-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_count_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='watch',
            field=models.IntegerField(default=0),
        ),
    ]
