# Generated by Django 3.1.1 on 2020-10-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_chapter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='priceusd',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
