# Generated by Django 3.1.1 on 2020-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_chapter_priceusd'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priceusd',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
