# Generated by Django 3.1.1 on 2020-11-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0009_auto_20201102_0944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_course_priceusd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Assegment',
                'verbose_name_plural': 'Assegment',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MockTest',
                'verbose_name_plural': 'MockTest',
            },
        ),
        migrations.CreateModel(
            name='MockTestProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsProgress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockTestPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='mockpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsPercentage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentsanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentProgress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='Assignmentpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentPercentage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AssegmentPercentage',
                'verbose_name_plural': 'AssegmentPercentage',
            },
        ),
    ]
