# Generated by Django 3.1.1 on 2020-11-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_assignmentspercentage_assignmentsprogress_assignmentstest_mocktest_mocktestpercentage_mocktestprogre'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentstest',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter'),
        ),
        migrations.AddField(
            model_name='assignmentstest',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
