# Generated by Django 3.1.1 on 2020-11-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20201102_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentsanswers', to='course.assignmentstest'),
        ),
        migrations.AlterField(
            model_name='mocktestprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestanswers', to='course.mocktest'),
        ),
    ]
