# Generated by Django 3.1.1 on 2020-11-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20201106_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberofMock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'NumberofMock',
                'verbose_name_plural': 'NumberofMock',
            },
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='mocktestpercentage',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='mocktestprogress',
            name='chapter',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='mock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock'),
        ),
        migrations.AddField(
            model_name='mocktestpercentage',
            name='mock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock'),
        ),
        migrations.AddField(
            model_name='mocktestprogress',
            name='mock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.numberofmock'),
        ),
    ]
