# Generated by Django 3.1.1 on 2020-11-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20201106_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentspercentage',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter'),
        ),
        migrations.AddField(
            model_name='assignmentsprogress',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter'),
        ),
        migrations.AddField(
            model_name='assignmentstest',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter'),
        ),
    ]
