# Generated by Django 3.1.1 on 2020-11-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20201106_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsprogress',
            options={'verbose_name': 'AssegmentProgres', 'verbose_name_plural': 'AssegmentProgres'},
        ),
        migrations.AlterModelOptions(
            name='mocktestprogress',
            options={'verbose_name': 'MockTestProgres', 'verbose_name_plural': 'MockTestProgres'},
        ),
    ]
