# Generated by Django 3.1.1 on 2020-11-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20201109_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentspercentage',
            options={'verbose_name': 'Assessment Percentage', 'verbose_name_plural': 'Assessment Percentage'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsprogress',
            options={'verbose_name': 'Assessment Progress', 'verbose_name_plural': 'Assessment Progress'},
        ),
        migrations.AlterModelOptions(
            name='assignmentstest',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessment'},
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': 'List Of File Uploaded', 'verbose_name_plural': 'List Of File Uploaded'},
        ),
        migrations.AlterModelOptions(
            name='mocktest',
            options={'verbose_name': 'Mock Test', 'verbose_name_plural': 'Mock Test'},
        ),
        migrations.AlterModelOptions(
            name='mocktestpercentage',
            options={'verbose_name': 'Mock Test Percentage', 'verbose_name_plural': 'Mock Test Percentage'},
        ),
        migrations.AlterModelOptions(
            name='mocktestprogress',
            options={'verbose_name': 'Mock Test Progress', 'verbose_name_plural': 'Mock Test Progress'},
        ),
        migrations.AlterModelOptions(
            name='numberofmock',
            options={'verbose_name': 'Number Of Mock', 'verbose_name_plural': 'Number Of Mock'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Course Purchase', 'verbose_name_plural': 'Course Purchase'},
        ),
    ]
