# Generated by Django 3.1.1 on 2020-10-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='studentimages')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studentanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentProgress', to='mcquestions.student')),
            ],
        ),
    ]
