# Generated by Django 3.1.1 on 2020-10-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentPercentage', to='mcquestions.student')),
            ],
        ),
    ]
