# Generated by Django 3.1.1 on 2020-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0003_auto_20201007_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(default=0, upload_to='studentimages'),
            preserve_default=False,
        ),
    ]
