# Generated by Django 3.1.1 on 2020-10-12 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0004_auto_20201009_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='otp_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='varifed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpercentage',
            name='coupancode',
            field=models.CharField(default=0, max_length=255, verbose_name='coupan code'),
            preserve_default=False,
        ),
    ]
