# Generated by Django 3.1.1 on 2020-10-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0005_auto_20201012_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AssignmentsTest',
                'verbose_name_plural': 'AssignmentsTest',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('is_correct', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MockTest',
                'verbose_name_plural': 'MockTest',
            },
        ),
        migrations.AlterModelOptions(
            name='mcquestions',
            options={'verbose_name': 'Mcquestions', 'verbose_name_plural': 'Mcquestions'},
        ),
    ]
