# Generated by Django 3.1.1 on 2020-11-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0006_auto_20201029_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsProgress', to='mcquestions.student')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='mockpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsPercentage', to='mcquestions.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmentsanswers', to='mcquestions.mcquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentProgress', to='mcquestions.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentsPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentag', models.CharField(max_length=255, verbose_name='Assignmentpercentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentPercentage', to='mcquestions.student')),
            ],
        ),
    ]
