# Generated by Django 3.1.1 on 2020-11-02 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcquestions', '0007_assignmentspercentage_assignmentsprogress_mocktestpercentage_mocktestprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentspercentage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentPercentage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignmentsprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentProgress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mocktestpercentage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsPercentage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mocktestprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MockTestsProgress', to=settings.AUTH_USER_MODEL),
        ),
    ]
