# Generated by Django 3.1.1 on 2020-11-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0008_auto_20201102_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentspercentage',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignmentsprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assignmentsprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='AssignmentsTest',
        ),
        migrations.DeleteModel(
            name='MockTest',
        ),
        migrations.RemoveField(
            model_name='mocktestpercentage',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mocktestprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mocktestprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='AssignmentsPercentage',
        ),
        migrations.DeleteModel(
            name='AssignmentsProgress',
        ),
        migrations.DeleteModel(
            name='MockTestPercentage',
        ),
        migrations.DeleteModel(
            name='MockTestProgress',
        ),
    ]
