# Generated by Django 3.1.1 on 2020-11-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0009_auto_20201102_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplechoice', models.CharField(max_length=255, verbose_name='number of questions show in mcquestions')),
                ('mock', models.CharField(max_length=255, verbose_name='number of questions show in mock')),
                ('assement', models.CharField(max_length=255, verbose_name='number of questions show in assement')),
            ],
        ),
    ]
