# Generated by Django 3.1.1 on 2020-11-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0010_numberofquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberofquestions',
            options={'verbose_name': 'NumberOfQuestions', 'verbose_name_plural': 'NumberOfQuestions'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'StudentProgres', 'verbose_name_plural': 'StudentProgres'},
        ),
    ]
