# Generated by Django 3.1.1 on 2020-11-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcquestions', '0011_auto_20201105_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcquestions',
            options={'verbose_name': 'MCQ Questions', 'verbose_name_plural': 'MCQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='numberofquestions',
            options={'verbose_name': 'Number Of Questions', 'verbose_name_plural': 'Number Of Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'List Of Student', 'verbose_name_plural': 'List Of Student'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress'},
        ),
    ]
