# Generated by Django 3.1.1 on 2020-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
