# Generated by Django 3.1.1 on 2020-10-19 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_paymentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=127, null=True)),
                ('course', models.CharField(blank=True, max_length=127, null=True)),
                ('otp', models.CharField(blank=True, max_length=127, null=True)),
                ('createat', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
