# Generated by Django 3.1.1 on 2020-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='started_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
