# Generated by Django 3.1.1 on 2020-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201022_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='started_at',
            field=models.DateField(),
        ),
    ]
