# Generated by Django 3.1.1 on 2020-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201026_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactUS', 'verbose_name_plural': 'contactUS'},
        ),
    ]
