# Generated by Django 3.1.1 on 2020-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201029_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
